import Navigation from '@/components/Navigation'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Andrés Salazar',
  description: 'Generated by AndresMelita',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='container-layout h-full' lang="en">
        <Navigation/>
        {children}
    </html>
  )
}
