import Navigation from '@/components/Navigation'
import background from "../assets/images/mountain.jpg";
import './globals.css'
import { Inter } from 'next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Andrés Salazar',
  description: 'Generated by AndresMelita',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className='container-layout h-full' lang="en">
      <div className='bg-[#00000036]'>
        <Image
            src={background}
            alt=""
            objectFit="cover"
            layout="fill"
            className="absolute -z-20"
          >  
        </Image>
      </div>
      <Navigation/>
      {children}
    </html>
  )
}
